
backend:
  name: github
  repo: your-username/your-repo  # ← 깃허브 사용자/저장소로 바꾸세요
  branch: main
  # GitHub OAuth 프록시를 쓰는 경우:
  base_url: https://bringup.vercel.app/
  auth_endpoint: /auth
media_folder: "media"
public_folder: "/media"
locale: "ja"
site_url: "https://your-username.github.io/your-repo/"

collections:
  - name: "site"
    label: "サイトデータ (buj-data.json)"
    files:
      - file: "buj-data.json"
        label: "buj-data.json"
        name: "bujdata"
        format: "json"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "サブタイトル", name: "subtitle", widget: "string" }
              - { label: "タグライン", name: "tagline", widget: "string" }
              - { label: "説明(複数行)", name: "description", widget: "list", field: {label: "段落", name: "p", widget: "text"} }
          - label: "History (沿革)"
            name: "history"
            widget: "list"
            fields:
              - { label: "日付(YYYY-MM-DD/YY-MM)", name: "date", widget: "string" }
              - { label: "本文", name: "text", widget: "string" }
          - label: "Activities (活動)"
            name: "activities"
            widget: "list"
            fields:
              - { label: "タイトル", name: "title", widget: "string" }
              - { label: "FontAwesome アイコン (fa-xxx)", name: "icon", widget: "string", required: false }
              - label: "詳細"
                name: "details"
                widget: "list"
                summary: "{{fields.key}}: {{fields.value}}"
                fields:
                  - {label: "キー", name: "key", widget: "string"}
                  - {label: "値", name: "value", widget: "string"}
              - { label: "本文", name: "content", widget: "text", required: false }
              - { label: "画像ID (img-001 等)", name: "images", widget: "list", field: {label: "ID", name: "id", widget: "string"}, required: false }
          - label: "News (お知らせ)"
            name: "news"
            widget: "list"
            fields:
              - { label: "日付(YYYY-MM-DD)", name: "date", widget: "string" }
              - { label: "タイトル", name: "title", widget: "string" }
              - { label: "時間", name: "time", widget: "string", required: false }
              - { label: "参加費", name: "fee", widget: "string", required: false }
              - { label: "本文", name: "content", widget: "text" }
          - label: "Access"
            name: "access"
            widget: "object"
            fields:
              - { label: "住所", name: "address", widget: "string" }
              - { label: "電話", name: "phone", widget: "string" }
              - { label: "メール", name: "email", widget: "string" }
              - { label: "担当者", name: "person", widget: "string" }
              - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
