backend:
  name: github
  repo: bringupjp/bringupjp
  branch: main
  base_url: https://bringup.vercel.app
  auth_endpoint: /auth

media_folder: "media"
public_folder: "/media"
locale: "ja"
site_url: "https://bringupjp.github.io/bringupjp/"

collections:
  - name: "site"
    label: "サイトデータ (buj-data.json)"
    files:
      - file: "buj-data.json"
        label: "buj-data.json"
        name: "bujdata"
        format: "json"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "サブタイトル", name: "subtitle", widget: "string" }
              - { label: "タグライン", name: "tagline", widget: "string" }
              - { label: "説明(複数行)", name: "description", widget: "list", field: {label: "段落", name: "p", widget: "text"} }
          - label: "History (沿革)"
            name: "history"
            widget: "list"
            fields:
              - { label: "日付(YYYY-MM-DD/YY-MM)", name: "date", widget: "string" }
              - { label: "本文", name: "text", widget: "string" }
          - label: "Activities (活動)"
            name: "activities"
            widget: "list"
            fields:
              - { label: "タイトル", name: "title", widget: "string" }
              - { label: "本文", name: "content", widget: "text", required: false }
              - label: "画像"
                name: "images"
                widget: "list"
                required: false
                field:
                  label: "画像"
                  name: "image"
                  widget: "image"

          # ✅ お知らせ 게시판 설정
          - label: "News (お知らせ)"
            name: "news"
            widget: "list"
            summary: "{{fields.date}} - {{fields.title}}"
            fields:
              - { label: "日付 (YYYY-MM-DD)", name: "date", widget: "string" }
              - { label: "タイトル", name: "title", widget: "string" }
              - { label: "本文", name: "content", widget: "markdown" }
              - label: "画像"
                name: "images"
                widget: "list"
                required: false
                field:
                  label: "画像"
                  name: "image"
                  widget: "image"

          - label: "Access"
            name: "access"
            widget: "object"
            fields:
              - { label: "住所", name: "address", widget: "string" }
              - { label: "電話", name: "phone", widget: "string" }
              - { label: "メール", name: "email", widget: "string" }
              - { label: "担当者", name: "person", widget: "string" }
              - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
